import {
    bulbasaur,
    ivysaur,
    venusaur,
    charmander,
    charmeleon,
    charizard,
    squirtle,
    wartortle,
    blastoise,
    caterpie,
    metapod,
    butterfree,
    weedle,
    kakuna,
    beedrill,
    pidgey,
    pidgeotto,
    pidgeot,
    rattata,
    raticate,
    spearow,
    fearow,
    ekans,
    arbok,
    pikachu,
    raichu,
    sandshrew,
    sandslash,
    nidoran_female,
    nidorina,
    nidoqueen,
    nidoran_male,
    nidorino,
    nidoking,
    clefairy,
    clefable,
    vulpix,
    ninetales,
    jigglypuff,
    wigglytuff,
    zubat,
    golbat,
    oddish,
    gloom,
    vileplume,
    paras,
    parasect,
    venonat,
    venomoth,
    diglett,
    dugtrio,
    meowth,
    persian,
    psyduck,
    golduck,
    mankey,
    primeape,
    growlithe,
    arcanine,
    poliwag,
    poliwhirl,
    poliwrath,
    abra,
    kadabra,
    alakazam,
    machop,
    machoke,
    machamp,
    bellsprout,
    weepinbell,
    victreebel,
    tentacool,
    tentacruel,
    geodude,
    graveler,
    golem,
    ponyta,
    rapidash,
    slowpoke,
    slowbro,
    magnemite,
    magneton,
    farfetchd,
    doduo,
    dodrio,
    seel,
    dewgong,
    grimer,
    muk,
    shellder,
    cloyster,
    gastly,
    haunter,
    gengar,
    onix,
    drowzee,
    hypno,
    krabby,
    kingler,
    voltorb,
    electrode,
    exeggcute,
    exeggutor,
    cubone,
    marowak,
    hitmonlee,
    hitmonchan,
    lickitung,
    koffing,
    weezing,
    rhyhorn,
    rhydon,
    chansey,
    tangela,
    kangaskhan,
    horsea,
    seadra,
    goldeen,
    seaking,
    staryu,
    starmie,
    mr_mime,
    scyther,
    jynx,
    electabuzz,
    magmar,
    pinsir,
    tauros,
    magikarp,
    gyarados,
    lapras,
    ditto,
    eevee,
    vaporeon,
    jolteon,
    flareon,
    porygon,
    omanyte,
    omastar,
    kabuto,
    kabutops,
    aerodactyl,
    snorlax,
    articuno,
    zapdos,
    moltres,
    dratini,
    dragonair,
    dragonite,
    mewtwo,
    mew
} from '../assets/pokemon_cards'

import {
    bulbasaur_audio,
    ivysaur_audio,
    venusaur_audio,
    charmander_audio,
    charmeleon_audio,
    charizard_audio,
    squirtle_audio,
    wartortle_audio,
    blastoise_audio,
    caterpie_audio,
    metapod_audio,
    butterfree_audio,
    weedle_audio,
    kakuna_audio,
    beedrill_audio,
    pidgey_audio,
    pidgeotto_audio,
    pidgeot_audio,
    rattata_audio,
    raticate_audio,
    spearow_audio,
    fearow_audio,
    ekans_audio,
    arbok_audio,
    pikachu_audio,
    raichu_audio,
    sandshrew_audio,
    sandslash_audio,
    nidoran_female_audio,
    nidorina_audio,
    nidoqueen_audio,
    nidoran_male_audio,
    nidorino_audio,
    nidoking_audio,
    clefairy_audio,
    clefable_audio,
    vulpix_audio,
    ninetales_audio,
    jigglypuff_audio,
    wigglytuff_audio,
    zubat_audio,
    golbat_audio,
    oddish_audio,
    gloom_audio,
    vileplume_audio,
    paras_audio,
    parasect_audio,
    venonat_audio,
    venomoth_audio,
    diglett_audio,
    dugtrio_audio,
    meowth_audio,
    persian_audio,
    psyduck_audio,
    golduck_audio,
    mankey_audio,
    primeape_audio,
    growlithe_audio,
    arcanine_audio,
    poliwag_audio,
    poliwhirl_audio,
    poliwrath_audio,
    abra_audio,
    kadabra_audio,
    alakazam_audio,
    machop_audio,
    machoke_audio,
    machamp_audio,
    bellsprout_audio,
    weepinbell_audio,
    victreebel_audio,
    tentacool_audio,
    tentacruel_audio,
    geodude_audio,
    graveler_audio,
    golem_audio,
    ponyta_audio,
    rapidash_audio,
    slowpoke_audio,
    slowbro_audio,
    magnemite_audio,
    magneton_audio,
    farfetchd_audio,
    doduo_audio,
    dodrio_audio,
    seel_audio,
    dewgong_audio,
    grimer_audio,
    muk_audio,
    shellder_audio,
    cloyster_audio,
    gastly_audio,
    haunter_audio,
    gengar_audio,
    onix_audio,
    drowzee_audio,
    hypno_audio,
    krabby_audio,
    kingler_audio,
    voltorb_audio,
    electrode_audio,
    exeggcute_audio,
    exeggutor_audio,
    cubone_audio,
    marowak_audio,
    hitmonlee_audio,
    hitmonchan_audio,
    lickitung_audio,
    koffing_audio,
    weezing_audio,
    rhyhorn_audio,
    rhydon_audio,
    chansey_audio,
    tangela_audio,
    kangaskhan_audio,
    horsea_audio,
    seadra_audio,
    goldeen_audio,
    seaking_audio,
    staryu_audio,
    starmie_audio,
    mr_mime_audio,
    scyther_audio,
    jynx_audio,
    electabuzz_audio,
    magmar_audio,
    pinsir_audio,
    tauros_audio,
    magikarp_audio,
    gyarados_audio,
    lapras_audio,
    ditto_audio,
    eevee_audio,
    vaporeon_audio,
    jolteon_audio,
    flareon_audio,
    porygon_audio,
    omanyte_audio,
    omastar_audio,
    kabuto_audio,
    kabutops_audio,
    aerodactyl_audio,
    snorlax_audio,
    articuno_audio,
    zapdos_audio,
    moltres_audio,
    dratini_audio,
    dragonair_audio,
    dragonite_audio,
    mewtwo_audio,
    mew_audio,
    unknown_audio
} from '../assets/description_audio'

export const pokemonDatabase = [
    {
        pokemon: "Bulbasaur",
        number: "0001",
        description: "Bulbasaur, the Seed Pokémon. A young Bulbasaur uses the nutrients from its seed for the energy it needs to grow. Researchers are unsure whether to classify Bulbasaur as a plant or animal. Bulbasaur are extremely tough and very difficult to capture in the wild.",
        type: ["Grass", "Poison"],
        card: bulbasaur,
        gif: "https://projectpokemon.org/images/normal-sprite/bulbasaur.gif",
        description_audio: bulbasaur_audio,
    },
    {
        pokemon: "Ivysaur",
        number: "0002",
        description: "Ivysaur, the Seed Pokémon. The evolved form of Bulbasaur. The bulb on its back absorbs nourishment and blooms into a large flower. It gives off an aroma when it is ready to bloom. When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.",
        type: ["Grass", "Poison"],
        card: ivysaur,
        gif: "https://projectpokemon.org/images/normal-sprite/ivysaur.gif",
        description_audio: ivysaur_audio,
    },
    {
        pokemon: "Venusaur",
        number: "0003",
        description: "Venusaur, the Seed Pokémon. The final form of the Bulbasaur evolution. Venusaur uses its large petals to capture sunlight and transform it into energy. It stays on the move to seek sunlight but when it is catching the sun's rays, Venasaur often remains quiet and still.",
        type: ["Grass", "Poison"],
        card: venusaur,
        gif: "https://projectpokemon.org/images/normal-sprite/venusaur.gif",
        description_audio: venusaur_audio,
    },
    {
        pokemon: "Charmander",
        number: "0004",
        description: "Charmander, the Flame Pokémon. A flame burns on the tip of its tail from birth, and shows the strength of its life force. If it is healthy, the flame burns brightly. It is said that a Charmander dies if its flame ever goes out.",
        type: ["Fire"],
        card: charmander,
        gif: "https://projectpokemon.org/images/normal-sprite/charmander.gif",
        description_audio: charmander_audio,
    },
    {
        pokemon: "Charmeleon",
        number: "0005",
        description: "Charmeleon, the Flame Pokémon. The evolved form of Charmander. Charmeleon has razor-sharp claws and its tail is exceptionally strong. When it swings its burning tail, it elevates the temperature to unbearably high levels.",
        type: ["Fire"],
        card: charmeleon,
        gif: "https://projectpokemon.org/images/normal-sprite/charmeleon.gif",
        description_audio: charmeleon_audio,
    },
    {
        pokemon: "Charizard",
        number: "0006",
        description: "Charizard, the Flame Pokémon. Charizard is the final evolved form of Charmander. When competing in intense battles, Charizard's flame becomes more intense as well. If Charizard becomes truly angered, the flame at the tip of its tail burns in a light blue shade.",
        type: ["Fire", "Flying"],
        card: charizard,
        gif: "https://projectpokemon.org/images/normal-sprite/charizard.gif",
        description_audio: charizard_audio,
    },
    {
        pokemon: "Squirtle",
        number: "0007",
        description: "Squirtle, the Tiny Turtle Pokémon. After birth, its back swells and hardens into a shell. Squirtle draws its long neck into its shell to launch incredible water attacks with amazing range and accuracy.",
        type: ["Water"],
        card: squirtle,
        gif: "https://projectpokemon.org/images/normal-sprite/squirtle.gif",
        description_audio: squirtle_audio,
    },
    {
        pokemon: "Wartortle",
        number: "0008",
        description: "Wartortle, the Turtle Pokémon. The evolved form of Squirtle. The tail is covered with a rich fur. It stores air in the fur before taking extended dives underwater. Its long, furry tail is a symbol of its age and wisdom.",
        type: ["Water"],
        card: wartortle,
        gif: "https://projectpokemon.org/images/normal-sprite/wartortle.gif",
        description_audio: wartortle_audio,
    },
    {
        pokemon: "Blastoise",
        number: "0009",
        description: "Blastoise, the Shellfish Pokémon. Blastoise is the final evolved form of Squirtle. It has spouts extending from its shell at the top. They spray water like cannons, hard enough to pierce concrete walls.",
        type: ["Water"],
        card: blastoise,
        gif: "https://projectpokemon.org/images/normal-sprite/blastoise.gif",
        description_audio: blastoise_audio,
    },
    {
        pokemon: "Caterpie",
        number: "0010",
        description: "Caterpie, the Worm Pokémon. Caterpie uses the suction cups on its feet to climb trees and feed on its favorite leaves. It has large, eye-like patterns on its head as protection. They are used to frighten off enemies.",
        type: ["Bug"],
        card: caterpie,
        gif: "https://projectpokemon.org/images/normal-sprite/caterpie.gif",
        description_audio: caterpie_audio,
    },
    {
        pokemon: "Metapod",
        number: "0011",
        description: "Metapod, the Cocoon Pokémon. Metapod is the evolved form of Caterpie. Using a hard shell to protect its body, it prepares for its next evolution. When it hardens, only the external shell is transformed. The inside remains tender.",
        type: ["Bug"],
        card: metapod,
        gif: "https://projectpokemon.org/images/normal-sprite/metapod.gif",
        description_audio: metapod_audio,
    },
    {
        pokemon: "Butterfree",
        number: "0012",
        description: "Butterfree, the Butterfly Pokémon. Butterfree's love of flower nectar draws it to seek out flowers, even if they don't have much pollen. In battle, it flaps its wings at high speed to release highly toxic dust into the air.",
        type: ["Bug", "Flying"],
        card: butterfree,
        gif: "https://projectpokemon.org/images/normal-sprite/butterfree.gif",
        description_audio: butterfree_audio,
    },
    {
        pokemon: "Weedle",
        number: "0013",
        description: "Weedle, the Hairy Bug Pokémon. Often found in forests and grassy areas, eating leaves. The stinger on this Pokémon's head guarantees that any attacker will get the point right where it hurts.",
        type: ["Bug", "Poison"],
        card: weedle,
        gif: "https://projectpokemon.org/images/normal-sprite/weedle.gif",
        description_audio: weedle_audio,
    },
    {
        pokemon: "Kakuna",
        number: "0014",
        description: "Kakuna, the Cocoon Pokémon. A transitional stage between Weedle and Beedrill. Almost incapable of moving, this Pokémon can only harden its shell to protect itself from predators until they evolve into deadly Beedrill and hatch.",
        type: ["Bug", "Poison"],
        card: kakuna,
        gif: "https://projectpokemon.org/images/normal-sprite/kakuna.gif",
        description_audio: kakuna_audio,
    },
    {
        pokemon: "Beedrill",
        number: "0015",
        description: "Beedrill, the Poison Bee Pokémon. This Pokémon is the evolved form of Weedle following its Kakuna state. Beedrill fly quickly and attack using the poison stingers on their four legs and tail. Caution, as Beedrill May appear in swarms.",
        type: ["Bug", "Poison"],
        card: beedrill,
        gif: "https://projectpokemon.org/images/normal-sprite/beedrill.gif",
        description_audio: beedrill_audio,
    },
    {
        pokemon: "Pidgey",
        number: "0016",
        description: "Pidgey, the Tiny Bird Pokémon. If attacked, it will often kick up sand to protect itself rather than fight back. Among all the flying Pokémon, it is the gentlest and easiest to capture, a perfect target for the beginning Pokémon trainer to test his or her Pokémon skills.",
        type: ["Normal", "Flying"],
        card: pidgey,
        gif: "https://projectpokemon.org/images/normal-sprite/pidgey.gif",
        description_audio: pidgey_audio,
    },
    {
        pokemon: "Pidgeotto",
        number: "0017",
        description: "Pidgeotto, the Bird Pokémon. The evolved form of Pidgey. It is armed with sharp claws and dives from the sky to capture its prey. Unlike the more gentle Pidgey, Pidgeotto can be dangerous. Approach with extreme caution.",
        type: ["Normal", "Flying"],
        card: pidgeotto,
        gif: "https://projectpokemon.org/images/normal-sprite/pidgeotto.gif",
        description_audio: pidgeotto_audio,
    },
    {
        pokemon: "Pidgeot",
        number: "0018",
        description: "Pidgeot, the Bird Pokémon. The evolved form of Pidgeotto. It can fly at Mach 2 speed at an altitude of nearly one mile. Its large talons are feared as wicked weapons.",
        type: ["Normal", "Flying"],
        card: pidgeot,
        gif: "https://projectpokemon.org/images/normal-sprite/pidgeot.gif",
        description_audio: pidgeot_audio,
    },
    {
        pokemon: "Rattata",
        number: "0019",
        description: "Rattata, the Mouse Pokémon. It likes cheese, nuts, fruits, and berries. It also comes out into open fields to steal food from careless travelers.",
        type: ["Normal"],
        card: rattata,
        gif: "https://projectpokemon.org/images/normal-sprite/rattata.gif",
        description_audio: rattata_audio,
    },
    {
        pokemon: "Raticate",
        number: "0020",
        description: "Raticate, the Mouse Pokémon. The evolved form of Rattata. Raticate can gnaw through anything with its ever-growing teeth. It uses its whiskers to maintain its balance.",
        type: ["Normal"],
        card: raticate,
        gif: "https://projectpokemon.org/images/normal-sprite/raticate.gif",
        description_audio: raticate_audio,
    },
    {
        pokemon: "Spearow",
        number: "0021",
        description: "Spearow, the Tiny Bird Pokémon. Unlike Pidgey, Spearow has a terrible attitude. It is very wild and will sometimes attack other Pokémon and humans.",
        type: ["Normal", "Flying"],
        card: spearow,
        gif: "https://projectpokemon.org/images/normal-sprite/spearow.gif",
        description_audio: spearow_audio,
    },
    {
        pokemon: "Fearow",
        number: "0022",
        description: "Fearow, the Beak Pokémon. The evolved form of Spearow. Fearow is a Pokémon that dates back many years. Its large, powerful wings allow it to fly for an entire day.",
        type: ["Normal", "Flying"],
        card: fearow,
        gif: "https://projectpokemon.org/images/normal-sprite/fearow.gif",
        description_audio: fearow_audio,
    },
    {
        pokemon: "Ekans",
        number: "0023",
        description: "Ekans, the Snake Pokémon. Moving silently and stealthily, it eats the eggs of birds, such as Pidgey and Spearow, whole. Ekans curls itself up in a spiral when it rests.",
        type: ["Poison"],
        card: ekans,
        gif: "https://projectpokemon.org/images/normal-sprite/ekans.gif",
        description_audio: ekans_audio,
    },
    {
        pokemon: "Arbok",
        number: "0024",
        description: "Arbok, the Cobra Pokémon. The evolved form of Ekans. It is rumored that the ferocious warning markings on its body differ from area to area.",
        type: ["Poison"],
        card: arbok,
        gif: "https://projectpokemon.org/images/normal-sprite/arbok.gif",
        description_audio: arbok_audio,
    },
    {
        pokemon: "Pikachu",
        number: "0025",
        description: "Pikachu, the Electric Mouse Pokémon. It can generate electric attacks from the electric pouches located in both of its cheeks. Pikachu's tail is sometimes struck by lightning.",
        type: ["Electric"],
        card: pikachu,
        gif: "https://projectpokemon.org/images/normal-sprite/pikachu-kantocap.gif",
        description_audio: pikachu_audio,
    },
    {
        pokemon: "Raichu",
        number: "0026",
        description: "Raichu, the Electric Mouse Pokémon. Raichu is the evolved form of Pikachu. Raichu uses its tail to discharge electricity into the ground. It can shock with more than 100,000 volts.",
        type: ["Electric"],
        card: raichu,
        gif: "https://projectpokemon.org/images/normal-sprite/raichu.gif",
        description_audio: raichu_audio,
    },
    {
        pokemon: "Sandshrew",
        number: "0027",
        description: "Sandshrew, the Mouse Pokémon. Sandshrew hates moisture and burrows deep underground in arid locations far from water. It only emerges to hunt for food and protects itself by curling into a ball.",
        type: ["Ground"],
        card: sandshrew,
        gif: "https://projectpokemon.org/images/normal-sprite/sandshrew.gif",
        description_audio: sandshrew_audio,
    },
    {
        pokemon: "Sandslash",
        number: "0028",
        description: "Sandslash, the Mouse Pokémon. The evolved form of Sandshrew. It attacks opponents with the quills on its back and uses its sharp claws to slash and quickly scurry about. If broken, they start to grow back in a day.",
        type: ["Ground"],
        card: sandslash,
        gif: "https://projectpokemon.org/images/normal-sprite/sandslash.gif",
        description_audio: sandslash_audio,
    },
    {
        pokemon: "Nidoran♀",
        number: "0029",
        description: "Nidoran, the Poison Pin Pokémon. Females are more sensitive to smells than males. While foraging, they'll use their whiskers to check wind direction and stay downwind of predators.",
        type: ["Poison"],
        card: nidoran_female,
        gif: "https://projectpokemon.org/images/normal-sprite/nidoran_f.gif",
        description_audio: nidoran_female_audio,
    },
    {
        pokemon: "Nidorina",
        number: "0030",
        description: "Nidorina, the Poison Pin Pokémon. The evolved form of the female Nidoran. The horn on its head has atrophied. It's thought that this happens so Nidorina's children won't get poked while their mother is feeding them.",
        type: ["Poison"],
        card: nidorina,
        gif: "https://projectpokemon.org/images/normal-sprite/nidorina.gif",
        description_audio: nidorina_audio,
    },
    {
        pokemon: "Nidoqueen",
        number: "0031",
        description: "Nidoqueen, the Drill Pokémon. The final evolution of the female Nidoran. Nidoqueen has thick skin covering its entire body, protecting it from whatever techniques are used against it.",
        type: ["Poison", "Ground"],
        card: nidoqueen,
        gif: "https://projectpokemon.org/images/normal-sprite/nidoqueen.gif",
        description_audio: nidoqueen_audio,
    },
    {
        pokemon: "Nidoran♂",
        number: "0032",
        description: "Nidoran, the Poison Pin Pokémon. Its horn contains a powerful poison, and is larger than the female's. Its large ears are always kept upright. If it senses danger, it will attack with a poisonous sting.",
        type: ["Poison"],
        card: nidoran_male,
        gif: "https://projectpokemon.org/images/normal-sprite/nidoran_m.gif",
        description_audio: nidoran_male_audio,
    },
    {
        pokemon: "Nidorino",
        number: "0033",
        description: "Nidorino, the Poison Pin Pokémon. The evolved form of the male Nidoran. With a horn that's harder than diamond, this Pokémon goes around shattering boulders as it searches for a moon stone.",
        type: ["Poison"],
        card: nidorino,
        gif: "https://projectpokemon.org/images/normal-sprite/nidorino.gif",
        description_audio: nidorino_audio,
    },
    {
        pokemon: "Nidoking",
        number: "0034",
        description: "Nidoking, the Drill Pokémon. The final evolution of the male Nidoran. When it goes on a rampage, it's impossible to control. But in the presence of a Nidoqueen it has lived with for a long time, Nidoking calms down.",
        type: ["Poison", "Ground"],
        card: nidoking,
        gif: "https://projectpokemon.org/images/normal-sprite/nidoking.gif",
        description_audio: nidoking_audio,
    },
    {
        pokemon: "Clefairy",
        number: "0035",
        description: "Clefairy, the Fairy Pokémon. This impish Pokémon is friendly and peaceful. It is believed to live inside Mount Moon, although very few have ever been seen by humans.",
        type: ["Fairy"],
        card: clefairy,
        gif: "https://projectpokemon.org/images/normal-sprite/clefairy.gif",
        description_audio: clefairy_audio,
    },
    {
        pokemon: "Clefable",
        number: "0036", 
        description: "Clefable, the Fairy Pokémon. The evolved form of Clefairy. Said to live in quiet, remote mountains, these unique creatures are among the rarest Pokémon in the world.",
        type: ["Fairy"],
        card: clefable,
        gif: "https://projectpokemon.org/images/normal-sprite/clefable.gif",
        description_audio: clefable_audio,
    },
    {
        pokemon: "Vulpix",
        number: "0037",
        description: "Vulpix, the Fox Pokémon. At the time of birth, it has just one tail. The tail splits from its tip as it grows older. If it is attacked by an enemy that is stronger than itself, it feigns injury to fool the enemy and escapes.",
        type: ["Fire"],
        card: vulpix,
        gif: "https://projectpokemon.org/images/normal-sprite/vulpix.gif",
        description_audio: vulpix_audio,
    },
    {
        pokemon: "Ninetales",
        number: "0038",
        description: "Ninetales, the Fox Pokémon. The evolved form of Vulpix. Very smart and very vengeful. Grabbing one of its many tails could result in a 1000-year curse. According to an enduring legend, 9 noble saints were united and reincarnated as this Pokémon.",
        type: ["Fire"],
        card: ninetales,
        gif: "https://projectpokemon.org/images/normal-sprite/ninetales.gif",
        description_audio: ninetales_audio,
    },
    {
        pokemon: "Jigglypuff",
        number: "0039",
        description: "Jigglypuff, the Balloon Pokémon. When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.",
        type: ["Normal", "Fairy"],
        card: jigglypuff,
        gif: "https://projectpokemon.org/images/normal-sprite/jigglypuff.gif",
        description_audio: jigglypuff_audio,
    },
    {
        pokemon: "Wigglytuff",
        number: "0040",
        description: "Wigglytuff, the Balloon Pokémon. The evolved form of Jigglypuff. It has very fine fur and its body is soft and rubbery. Take care not to make it angry, or it may inflate itself to an enormous size and hit with a body slam.",
        type: ["Normal", "Fairy"],
        card: wigglytuff,
        gif: "https://projectpokemon.org/images/normal-sprite/wigglytuff.gif",
        description_audio: wigglytuff_audio,
    },
    {
        pokemon: "Zubat",
        number: "0041",
        description: "Zubat, the Bat Pokémon. It is a flying and poison type Pokémon that uses ultrasonic waves to identify and approach targets.. Zubat live in caves and hate to fly outside in daylight.",
        type: ["Poison", "Flying"],
        card: zubat,
        gif: "https://projectpokemon.org/images/normal-sprite/zubat.gif",
        description_audio: zubat_audio,
    },
    {
        pokemon: "Golbat",
        number: "0042",
        description: "Golbat, the Bat Pokémon. The evolved form of Zubat. Attacking with its sharp fangs, this Pokémon can drain 300 cubic centimeters of blood per bite. Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.",
        type: ["Poison", "Flying"],
        card: golbat,
        gif: "https://projectpokemon.org/images/normal-sprite/golbat.gif",
        description_audio: golbat_audio,
    },
    {
        pokemon: "Oddish",
        number: "0043",
        description: "Oddish, the Weed Pokémon. During the day, it keeps its face buried in the ground. At night, Oddish is typically found roaming the forest, scattering pollen as it walks around.",
        type: ["Grass", "Poison"],
        card: oddish,
        gif: "https://projectpokemon.org/images/normal-sprite/oddish.gif",
        description_audio: oddish_audio,
    },
    {
        pokemon: "Gloom",
        number: "0044",
        description: "Gloom, the Weed Pokémon. The evolved form of Oddish. The fluid that oozes from its mouth isn't drool. It is a nectar that is used to attract prey. Gloom gives off a powerful aroma that can cause those who smell it to faint from two miles away.",
        type: ["Grass", "Poison"],
        card: gloom,
        gif: "https://projectpokemon.org/images/normal-sprite/gloom.gif",
        description_audio: gloom_audio,
    },
    {
        pokemon: "Vileplume",
        number: "0045",
        description: "Vileplume, the Flower Pokémon. Vileplume is the final evolved form of Oddish. Using the largest flower petals in the world, it spreads large clouds of pollen that cause allergic reactions.",
        type: ["Grass", "Poison"],
        card: vileplume,
        gif: "https://projectpokemon.org/images/normal-sprite/vileplume.gif",
        description_audio: vileplume_audio,
    },
    {
        pokemon: "Paras",
        number: "0046",
        description: "Paras, the Mushroom Pokémon. Paras burrows under the ground to gnaw on tree roots. The rare mushrooms on its back absorb most of the nutrition from the bug host.",
        type: ["Bug", "Grass"],
        card: paras,
        gif: "https://projectpokemon.org/images/normal-sprite/paras.gif",
        description_audio: paras_audio,
    },
    {
        pokemon: "Parasect",
        number: "0047",
        description: "Parasect, the Mushroom Pokémon. A host-parasite pair in which the parasite mushroom has taken over the host bug. The bug host is drained of energy by the mushroom on its back. The mushroom appears to do all the thinking.",
        type: ["Bug", "Grass"],
        card: parasect,
        gif: "https://projectpokemon.org/images/normal-sprite/parasect.gif",
        description_audio: parasect_audio,
    },
    {
        pokemon: "Venonat",
        number: "0048",
        description: "Venonat, the Insect Pokémon. Its eyes function as radar, allowing it to see in the dark. Poison oozes from all over its body. It catches small bug Pokémon at night that are attracted by light.",
        type: ["Bug", "Poison"],
        card: venonat,
        gif: "https://projectpokemon.org/images/normal-sprite/venonat.gif",
        description_audio: venonat_audio,
    },
    {
        pokemon: "Venomoth",
        number: "0049",
        description: "Venomoth, the Poison Moth Pokémon. The evolved form of Venonat. The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.",
        type: ["Bug", "Poison"],
        card: venomoth,
        gif: "https://projectpokemon.org/images/normal-sprite/venomoth.gif",
        description_audio: venomoth_audio,
    },
    {
        pokemon: "Diglett",
        number: "0050",
        description: "Diglett, the Mole Pokémon. Lives about one yard underground where it feeds on plant roots. The movement of these ground Pokémon can be easily detected by their tracks of upturned earth.",
        type: ["Ground"],
        card: diglett,
        gif: "https://projectpokemon.org/images/normal-sprite/diglett.gif",
        description_audio: diglett_audio,
    },
    {
        pokemon: "Dugtrio",
        number: "0051",
        description: "Dugtrio, the Mole Pokémon. The evolved form of Diglett. A team of Diglett triplets, it triggers huge earthquakes by burrowing 60 miles underground.",
        type: ["Ground"],
        card: dugtrio,
        gif: "https://projectpokemon.org/images/normal-sprite/dugtrio.gif",
        description_audio: dugtrio_audio,
    },
    {
        pokemon: "Meowth",
        number: "0052",
        description: "Meowth, the Scratch Cat Pokémon. Meowth loves to roam at night to gather coins and other objects that sparkle, but it spends most of the daylight hours sleeping.",
        type: ["Normal"],
        card: meowth,
        gif: "https://projectpokemon.org/images/normal-sprite/meowth.gif",
        description_audio: meowth_audio,
    },
    {
        pokemon: "Persian",
        number: "0053",
        description: "Persian, the Classy Cat Pokémon. Although its fur has many admirers, it is tough to raise as a pet because of its fickle meanness. The gem in its forehead glows on its own.",
        type: ["Normal"],
        card: persian,
        gif: "https://projectpokemon.org/images/normal-sprite/persian.gif",
        description_audio: persian_audio,
    },
    {
        pokemon: "Psyduck",
        number: "0054",
        description: "Psyduck, the Duck Pokémon. Psyduck constantly suffers from a headache. The more its head hurts, the stronger its psychic power.",
        type: ["Water"],
        card: psyduck,
        gif: "https://projectpokemon.org/images/normal-sprite/psyduck.gif",
        description_audio: psyduck_audio,
    },
    {
        pokemon: "Golduck",
        number: "0055",
        description: "Golduck, the Duck Pokémon. The evolved form of Psyduck. Golduck is very adept at using its webbed hands and feet, making it the fastest swimming Pokémon of all.", 
        type: ["Water"],
        card: golduck,
        gif: "https://projectpokemon.org/images/normal-sprite/golduck.gif",
        description_audio: golduck_audio,
    },
    {
        pokemon: "Mankey",
        number: "0056",
        description: "Mankey, the Pig Monkey Pokémon. Mankey live in groups among the treetops. Known for its superior footwork, it is extremely quick to anger and will not hesitate to attack anything.",
        type: ["Fighting"],
        card: mankey,
        gif: "https://projectpokemon.org/images/normal-sprite/mankey.gif",
        description_audio: mankey_audio,
    },
    {
        pokemon: "Primeape",
        number: "0057",
        description: "Primeape, the Pig Monkey Pokémon. If you make eye contact with this evolved form of Mankey, it will chase you forever.",
        type: ["Fighting"],
        card: primeape,
        gif: "https://projectpokemon.org/images/normal-sprite/primeape.gif",
        description_audio: primeape_audio,
    },
    {
        pokemon: "Growlithe",
        number: "0058",
        description: "Growlithe, the Puppy Pokémon of pleasant demeanor and great diligence. Very protective of its territory, it will bark and bite to repel intruders from its space.",
        type: ["Fire"],
        card: growlithe,
        gif: "https://projectpokemon.org/images/normal-sprite/growlithe.gif",
        description_audio: growlithe_audio,
    },
    {
        pokemon: "Arcanine",
        number: "0059",
        description: "Arcanine, the Legendary Pokémon. The evolved form of Growlithe. Arcanine is known for its bravery and fierce loyalty. It has been admired since the past for its beauty. It runs agilely as if on wings.",
        type: ["Fire"],
        card: arcanine,
        gif: "https://projectpokemon.org/images/normal-sprite/arcanine.gif",
        description_audio: arcanine_audio,
    },
    {
        pokemon: "Poliwag",
        number: "0060",
        description: "Poliwag, the Tadpole Pokémon. Its newly grown legs prevent it from running. Poliwag also has no arms but its tail makes it a strong swimmer.",
        type: ["Water"],
        card: poliwag,
        gif: "https://projectpokemon.org/images/normal-sprite/poliwag.gif",
        description_audio: poliwag_audio,
    },
    {
        pokemon: "Poliwhirl",
        number: "0061",
        description: "Poliwhirl, the Tadpole Pokémon. It has highly developed muscles which allow Poliwhirl to move efficiently on land, but it is even more agile in water.",
        type: ["Water"],
        card: poliwhirl,
        gif: "https://projectpokemon.org/images/normal-sprite/poliwhirl.gif",
        description_audio: poliwhirl_audio,
    },
    {
        pokemon: "Poliwrath",
        number: "0062",
        description: "Poliwrath, the Tadpole Pokémon. Poliwrath is an excellent swimmer and its powerful muscles make its attacks extremely effective. Easily overtakes the best human swimmers.",
        type: ["Water", "Fighting"],
        card: poliwrath,
        gif: "https://projectpokemon.org/images/normal-sprite/poliwrath.gif",
        description_audio: poliwrath_audio,
    },
    {
        pokemon: "Abra",
        number: "0063",
        description: "Abra, the Psi Pokémon. It sleeps 18 hours a day, but employs telekinesis even while sleeping. Using its ability to read minds, it will identify impending danger and Teleport to safety.",
        type: ["Psychic"],
        card: abra,
        gif: "https://projectpokemon.org/images/normal-sprite/abra.gif",
        description_audio: abra_audio,
    },
    {
        pokemon: "Kadabra",
        number: "0064",
        description: "Kadabra, the Psi Pokémon. The evolved form of Abra. Using its psychic power, Kadabra levitates as it sleeps. It emits special alpha waves from its body that induce headaches just by being close by.",
        type: ["Psychic"],
        card: kadabra,
        gif: "https://projectpokemon.org/images/normal-sprite/kadabra.gif",
        description_audio: kadabra_audio,
    },
    {
        pokemon: "Alakazam",
        number: "0065",
        description: "Alakazam, the Psi Pokémon. The evolved form of Kadabra. With a brain like a supercomputer, it possesses many different supernatural powers. Its intelligence quotient is said to be 5,000.",
        type: ["Psychic"],
        card: alakazam,
        gif: "https://projectpokemon.org/images/normal-sprite/alakazam.gif",
        description_audio: alakazam_audio,
    },
    {
        pokemon: "Machop",
        number: "0066",
        description: "Machop, the Superpower Pokémon. Machop's body is pure muscle and it loves to build its muscles. It trains in all styles of martial arts to become even stronger.",
        type: ["Fighting"],
        card: machop,
        gif: "https://projectpokemon.org/images/normal-sprite/machop.gif",
        description_audio: machop_audio,
    },
    {
        pokemon: "Machoke",
        number: "0067",
        description: "Machoke, the Superpower Pokémon. Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions. Without it, this Pokémon would be unstoppable.",
        type: ["Fighting"],
        card: machoke,
        gif: "https://projectpokemon.org/images/normal-sprite/machoke.gif",
        description_audio: machoke_audio,
    },
    {
        pokemon: "Machamp",
        number: "0068",
        description: "Machamp, the superpower Pokémon. One arm alone can move mountains. Using all four arms, this Pokémon fires off powerful punches that can send the victim clear over the horizon.",
        type: ["Fighting"],
        card: machamp,
        gif: "https://projectpokemon.org/images/normal-sprite/machamp.gif",
        description_audio: machamp_audio,
    },
    {
        pokemon: "Bellsprout",
        number: "0069",
        description: "Bellsprout, the Flower Pokémon. A carnivorous Pokémon that traps and eats bugs. It uses its root feet to soak up needed moisture. Bellsprout loves high temperatures and humidity.",
        type: ["Grass", "Poison"],
        card: bellsprout,
        gif: "https://projectpokemon.org/images/normal-sprite/bellsprout.gif",
        description_audio: bellsprout_audio,
    },
    {
        pokemon: "Weepinbell",
        number: "0070",
        description: "Weepinbell, the Flycatcher Pokémon. The evolved form of Bellsprout. It spits out Poison Powder to immobilize the enemy and then finishes it with a spray of Acid.",
        type: ["Grass", "Poison"],
        card: weepinbell,
        gif: "https://projectpokemon.org/images/normal-sprite/weepinbell.gif",
        description_audio: weepinbell_audio,
    },
    {
        pokemon: "Victreebel",
        number: "0071",
        description: "Victreebel, the Flycatcher Pokémon. It lures prey into its mouth with a nectar-like aroma. Swallowed whole, the prey is melted in a day, bones and all.",
        type: ["Grass", "Poison"],
        card: victreebel,
        gif: "https://projectpokemon.org/images/normal-sprite/victreebel.gif",
        description_audio: victreebel_audio,
    },
    {
        pokemon: "Tentacool",
        number: "0072",
        description: "Tentacool, the Jellyfish Pokémon. Tentacool drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid. 99 percent of its body is made up of water.",
        type: ["Water", "Poison"],
        card: tentacool,
        gif: "https://projectpokemon.org/images/normal-sprite/tentacool.gif",
        description_audio: tentacool_audio,
    },
    {
        pokemon: "Tentacruel",
        number: "0073",
        description: "Tentacruel, the Jellyfish Pokémon. The evolved form of the Tentacool. Its 80 tentacles can stretch and contract freely and serve as a powerful weapon. It is known as the gangster of the sea.",
        type: ["Water", "Poison"],
        card: tentacruel,
        gif: "https://projectpokemon.org/images/normal-sprite/tentacruel.gif",
        description_audio: tentacruel_audio,
    },
    {
        pokemon: "Geodude",
        number: "0074",
        description: "Geodude, the Rock Pokémon. Geodude's habitat is mostly made up of mountain paths. If carelessly stepped on, Geodude will swing its fists angrily.",
        type: ["Rock", "Ground"],
        card: geodude,
        gif: "https://projectpokemon.org/images/normal-sprite/geodude.gif",
        description_audio: geodude_audio,
    },
    {
        pokemon: "Graveler",
        number: "0075",
        description: "Graveler, the Rock Pokémon. As a slow walker, it rolls to move. It pays no attention to any object that happens to be in its path.",
        type: ["Rock", "Ground"],
        card: graveler,
        gif: "https://projectpokemon.org/images/normal-sprite/graveler.gif",
        description_audio: graveler_audio,
    },
    {
        pokemon: "Golem",
        number: "0076",
        description: "Golem, the Megaton Pokémon. It is enclosed in a hard shell that is as rugged as slabs of rock. Once a year it sheds its bedrock shell and grows larger.",
        type: ["Rock", "Ground"],
        card: golem,
        gif: "https://projectpokemon.org/images/normal-sprite/golem.gif",
        description_audio: golem_audio,
    },
    {
        pokemon: "Ponyta",
        number: "0077",
        description: "Ponyta, the Fire Horse Pokémon. About an hour after birth, Ponyta's fiery mane and tail grow out. Capable of jumping incredibly high, its hooves and sturdy legs absorb the impact of a hard landing.",
        type: ["Fire"],
        card: ponyta,
        gif: "https://projectpokemon.org/images/normal-sprite/ponyta.gif",
        description_audio: ponyta_audio,
    },
    {
        pokemon: "Rapidash",
        number: "0078",
        description: "Rapidash, the Fire Horse Pokémon. Very competitive, this Pokémon will chase anything fast in the hopes of racing it. It gallops at nearly 150 miles per hour.",
        type: ["Fire"],
        card: rapidash,
        gif: "https://projectpokemon.org/images/normal-sprite/rapidash.gif",
        description_audio: rapidash_audio,
    },
    {
        pokemon: "Slowpoke",
        number: "0079",
        description: "Slowpoke, the Dopey Pokémon. Incredibly slow and dopey. It takes 5 seconds for it to feel pain when under attack. Slowpoke is always lost in thought, but nobody knows what it is pondering.",
        type: ["Water", "Psychic"],
        card: slowpoke,
        gif: "https://projectpokemon.org/images/normal-sprite/slowpoke.gif",
        description_audio: slowpoke_audio,
    },
    {
        pokemon: "Slowbro",
        number: "0080",
        description: "Slowbro, the Hermit Crab Pokémon. If a Shellder bites a Slowpoke's tail, Slowpoke evolves into Slowbro. Slowbro lives lazily by the sea. If the Shellder on its tail comes off, it becomes a Slowpoke again.",
        type: ["Water", "Psychic"],
        card: slowbro,
        gif: "https://projectpokemon.org/images/normal-sprite/slowbro.gif",
        description_audio: slowbro_audio,
    },
    {
        pokemon: "Magnemite",
        number: "0081",
        description: "Magnemite, the Magnet Pokémon. It is born with the ability to defy gravity. Magnemite is able to float through the air and emits thunder waves through its magnet-shaped units located on its sides.",
        type: ["Electric", "Steel"],
        card: magnemite,
        gif: "https://projectpokemon.org/images/normal-sprite/magnemite.gif",
        description_audio: magnemite_audio,
    },
    {
        pokemon: "Magneton",
        number: "0082",
        description: "Magneton, the Magnet Pokémon. The evolved form of Magnemite. Formed by several Magnemites linked together. They frequently appear when sunspots flare up and can generate strange radio signals.",
        type: ["Electric", "Steel"],
        card: magneton,
        gif: "https://projectpokemon.org/images/normal-sprite/magneton.gif",
        description_audio: magneton_audio,
    },
    {
        pokemon: "Farfetch'd",
        number: "0083",
        description: "Farfetch'd, the Wild Duck Pokémon. The sprig of green onions it holds is its weapon. It is used much like a metal sword. Farfetch'd makes a delicious meal, especially when cooked with leek. Because of this, Farfetch'd is nearly extinct.",
        type: ["Normal", "Flying"],
        card: farfetchd,
        gif: "https://projectpokemon.org/images/normal-sprite/farfetchd.gif",
        description_audio: farfetchd_audio,
    },
    {
        pokemon: "Doduo",
        number: "0084",
        description: "Doduo, the Twin Bird Pokémon. A bird that makes up for its poor flying with its fast foot speed. Its twin heads have exactly the same genes and battle in perfect sync with each other.",
        type: ["Normal", "Flying"],
        card: doduo,
        gif: "https://projectpokemon.org/images/normal-sprite/doduo.gif",
        description_audio: doduo_audio,
    },
    {
        pokemon: "Dodrio",
        number: "0085",
        description: "Dodrio, the Triple Bird Pokémon. Dodrio uses its three brains to execute complex plans. While two heads sleep, one head stays awake. Its three heads represent joy, sorrow, and anger.",
        type: ["Normal", "Flying"],
        card: dodrio,
        gif: "https://projectpokemon.org/images/normal-sprite/dodrio.gif",
        description_audio: dodrio_audio,
    },
    {
        pokemon: "Seel",
        number: "0086",
        description: "Seel, the Sea Lion Pokémon. The protrusion on its head is very hard. It is used for bashing through thick ice. Loves freezing cold conditions.",
        type: ["Water"],
        card: seel,
        gif: "https://projectpokemon.org/images/normal-sprite/seel.gif",
        description_audio: seel_audio,
    },
    {
        pokemon: "Dewgong",
        number: "0087",
        description: "Dewgong, the Sea Lion Pokémon. The evolved form of Seel. This water-ice Pokémon stores thermal energy in its body. Dewgong swims at a steady 8 knots even in intensely cold waters.",
        type: ["Water", "Ice"],
        card: dewgong,
        gif: "https://projectpokemon.org/images/normal-sprite/dewgong.gif",
        description_audio: dewgong_audio,
    },
    {
        pokemon: "Grimer",
        number: "0088",
        description: "Grimer, the Sludge Pokémon. Born from sludge, these Pokémon now gather in polluted places and increase the bacteria in their bodies.",
        type: ["Poison"],
        card: grimer,
        gif: "https://projectpokemon.org/images/normal-sprite/grimer.gif",
        description_audio: grimer_audio,
    },
    {
        pokemon: "Muk",
        number: "0089",
        description: "Muk, the Sludge Pokémon. The evolved form of Grimer. It's thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.",
        type: ["Poison"],
        card: muk,
        gif: "https://projectpokemon.org/images/normal-sprite/muk.gif",
        description_audio: muk_audio,
    },
    {
        pokemon: "Shellder",
        number: "0090",
        description: "Shellder, the Bivalve Pokémon. It is encased in a shell that is harder than diamond and repels any kind of attack. Inside, however, it is surprisingly tender.",
        type: ["Water"],
        card: shellder,
        gif: "https://projectpokemon.org/images/normal-sprite/shellder.gif",
        description_audio: shellder_audio,
    },
    {
        pokemon: "Cloyster",
        number: "0091",
        description: "Cloyster, the Bivalve Pokémon. Its shell is incredibly strong and resistant to even a bomb. Its shell only opens when it attacks. It also shoots spikes from the shell.",
        type: ["Water", "Ice"],
        card: cloyster,
        gif: "https://projectpokemon.org/images/normal-sprite/cloyster.gif",
        description_audio: cloyster_audio,
    },
    {
        pokemon: "Gastly",
        number: "0092",
        description: "Gastly, the Gas Pokémon. Almost invisible, this gaseous Pokémon cloaks the target and puts it to sleep without notice. Will not appear if it is very windy.", 
        type: ["Ghost", "Poison"],
        card: gastly,
        gif: "https://projectpokemon.org/images/normal-sprite/gastly.gif",
        description_audio: gastly_audio,
    },
    {
        pokemon: "Haunter",
        number: "0093",
        description: "Haunter, the Gas Pokémon. The evolved form of Gastly. Haunter can watch opponents by hiding in walls. By licking, it saps the victim's life. It causes shaking that won't stop until the victim's demise.",
        type: ["Ghost", "Poison"],
        card: haunter,
        gif: "https://projectpokemon.org/images/normal-sprite/haunter.gif",
        description_audio: haunter_audio,
    },
    {
        pokemon: "Gengar",
        number: "0094",
        description: "Gengar, the Shadow Pokémon. The evolved form of Haunter. To steal the life from its target, Gengar slips into the prey's shadow. Under a full moon, this Pokémon likes to mimic the shadows of people and laugh at their fright.",
        type: ["Ghost", "Poison"],
        card: gengar,
        gif: "https://projectpokemon.org/images/normal-sprite/gengar.gif",
        description_audio: gengar_audio,
    },
    {
        pokemon: "Onix",
        number: "0095",
        description: "Onix, the Rock Snake Pokémon. By twisting its large and powerful body, Onix can quickly bore through the ground at 50 miles per hour. As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.",
        type: ["Rock", "Ground"],
        card: onix,
        gif: "https://projectpokemon.org/images/normal-sprite/onix.gif",
        description_audio: onix_audio,
    },
    {
        pokemon: "Drowzee",
        number: "0096",
        description: "Drowzee, the Hypnosis Pokémon. Said to be a descendant of the dream-eating tapir, it puts its enemy to sleep and eats the victim's dreams. Occasionally gets sick from eating bad dreams.",
        type: ["Psychic"],
        card: drowzee,
        gif: "https://projectpokemon.org/images/normal-sprite/drowzee.gif",
        description_audio: drowzee_audio,
    },
    {
        pokemon: "Hypno",
        number: "0097",
        description: "Hypno, the Hypnosis Pokémon. It carries a pendulum-like device and performs hypnotic attacks. When it locks eyes with an enemy, it will use a mix of psi moves Hypnosis and Confusion.",
        type: ["Psychic"],
        card: hypno,
        gif: "https://projectpokemon.org/images/normal-sprite/hypno.gif",
        description_audio: hypno_audio,
    },
    {
        pokemon: "Krabby",
        number: "0098",
        description: "Krabby, the River Crab Pokémon. Krabby can be found on beaches and seashores. Krabby's large pincers grow back even if they are torn out of their sockets.",
        type: ["Water"],
        card: krabby,
        gif: "https://projectpokemon.org/images/normal-sprite/krabby.gif",
        description_audio: krabby_audio,
    },
    {
        pokemon: "Kingler",
        number: "0099",
        description: "Kingler, the Pincer Pokémon. The evolved form of Krabby. Kingler's claws can pinch with the strength of 10,000 horsepower. However, because it is so heavy, it can be difficult to aim.",
        type: ["Water"],
        card: kingler,
        gif: "https://projectpokemon.org/images/normal-sprite/kingler.gif",
        description_audio: kingler_audio,
    },
    {
        pokemon: "Voltorb",
        number: "0100",
        description: "Voltorb, the Ball Pokémon. Voltorb are usually found in power plants. Easily mistaken for a Poké Ball, they have zapped many people. It has an extreme personality, and at times self-destructs.",
        type: ["Electric"],
        card: voltorb,
        gif: "https://projectpokemon.org/images/normal-sprite/voltorb.gif",
        description_audio: voltorb_audio,
    },
    {
        pokemon: "Electrode",
        number: "0101",
        description: "Electrode, the Ball Pokémon. The evolved form of Voltorb. Electrode stores high concentrations of electric energy in its body which causes this Pokémon to explode unpredictably. The more energy it charges up, the faster it gets.",
        type: ["Electric"],
        card: electrode,
        gif: "https://projectpokemon.org/images/normal-sprite/electrode.gif",
        description_audio: electrode_audio,
    },
    {
        pokemon: "Exeggcute",
        number: "0102",
        description: "Exeggcute, the Egg Pokémon. If you touch one of Exeggcute's heads, mistaking it for an egg, the other heads will quickly gather and attack you in a swarm.",
        type: ["Grass", "Psychic"],
        card: exeggcute,
        gif: "https://projectpokemon.org/images/normal-sprite/exeggcute.gif",
        description_audio: exeggcute_audio,
    },
    {
        pokemon: "Exeggutor",
        number: "0103",
        description: "Exeggutor, the Coconut Pokémon. Each coconut has a distinct face and its own character. Legend has it that on rare occasions, one of its heads will drop off and continue on as an Exeggcute.",
        type: ["Grass", "Psychic"],
        card: exeggutor,
        gif: "https://projectpokemon.org/images/normal-sprite/exeggutor.gif",
        description_audio: exeggutor_audio,
    },
    {
        pokemon: "Cubone",
        number: "0104",
        description: "Cubone, the Lonely Pokémon. When the memory of its departed mother brings it to tears, its cries echo mournfully within the skull it wears on its head.",
        type: ["Ground"],
        card: cubone,
        gif: "https://projectpokemon.org/images/normal-sprite/cubone.gif",
        description_audio: cubone_audio,
    },
    {
        pokemon: "Marowak",
        number: "0105",
        description: "Marowak, the Bone Keeper Pokémon. The evolved form of Cubone. Marowak faces its opponents bravely, using a bone as a weapon. It throws the bone skillfully like a boomerang to knock out targets.",
        type: ["Ground"],
        card: marowak,
        gif: "https://projectpokemon.org/images/normal-sprite/marowak.gif",
        description_audio: marowak_audio,
    },
    {
        pokemon: "Hitmonlee",
        number: "0106",
        description: "Hitmonlee, the Kicking Pokémon. Hitmonlee can extend and retract its legs at will to kick opponents from almost any distance. When kicking, the sole of its foot turns as hard as a diamond on impact and destroys its enemy.",
        type: ["Fighting"],
        card: hitmonlee,
        gif: "https://projectpokemon.org/images/normal-sprite/hitmonlee.gif",
        description_audio: hitmonlee_audio,
    },
    {
        pokemon: "Hitmonchan",
        number: "0107",
        description: "Hitmonchan, the Punching Pokémon. Hitmonchan is a skilled fighting Pokémon that fires punches in lightning fast volleys that are impossible to see. It can punch its way through a concrete wall in the same way as a drill.",
        type: ["Fighting"],
        card: hitmonchan,
        gif: "https://projectpokemon.org/images/normal-sprite/hitmonchan.gif",
        description_audio: hitmonchan_audio,
    },
    {
        pokemon: "Lickitung",
        number: "0108",
        description: "Lickitung, the Licking Pokémon. It uses a tongue that is more than twice the length of its body to battle as well as to gather food.  Its licks can cause paralysis.",
        type: ["Normal"],
        card: lickitung,
        gif: "https://projectpokemon.org/images/normal-sprite/lickitung.gif",
        description_audio: lickitung_audio,
    },
    {
        pokemon: "Koffing",
        number: "0109",
        description: "Koffing, the Poison Gas Pokémon. Koffing hovers in the air thanks to the poisonous gases it contains. Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.",
        type: ["Poison"],
        card: koffing,
        gif: "https://projectpokemon.org/images/normal-sprite/koffing.gif",
        description_audio: koffing_audio,
    },
    {
        pokemon: "Weezing",
        number: "0110",
        description: "Weezing, the Poison Gas Pokémon. A twinned Koffing that forms on rare occasions where poisonous gases pool. It lives and grows by absorbing dust, germs and poison gases that are contained in toxic waste and garbage.",
        type: ["Poison"],
        card: weezing,
        gif: "https://projectpokemon.org/images/normal-sprite/weezing.gif",
        description_audio: weezing_audio,
    },
    {
        pokemon: "Rhyhorn",
        number: "0111",
        description: "Rhyhorn, the Spikes Pokémon. Rhyhorn recklessly charges straight ahead, trampling over anything that gets in its way. Its massive bones are 1000 times harder than human bones.",
        type: ["Ground", "Rock"],
        card: rhyhorn,
        gif: "https://projectpokemon.org/images/normal-sprite/rhyhorn.gif",
        description_audio: rhyhorn_audio,
    },
    {
        pokemon: "Rhydon",
        number: "0112",
        description: "Rhydon, the Drill Pokémon. The evolved form of Rhyhorn. Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.",
        type: ["Ground", "Rock"],
        card: rhydon,
        gif: "https://projectpokemon.org/images/normal-sprite/rhydon.gif",
        description_audio: rhydon_audio,
    },
    {
        pokemon: "Chansey",
        number: "0113",
        description: "Chansey, the Egg Pokémon. A rare and elusive Pokémon that is said to bring happiness to those who manage to get it. Chansey is a kind Pokémon who shares its egg with those who are sick or injured.",
        type: ["Normal"],
        card: chansey,
        gif: "https://projectpokemon.org/images/normal-sprite/chansey.gif",
        description_audio: chansey_audio,
    },
    {
        pokemon: "Tangela",
        number: "0114",
        description: "Tangela, the Vine Pokémon. The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks. The vines are said to never stop growing.",
        type: ["Grass"],
        card: tangela,
        gif: "https://projectpokemon.org/images/normal-sprite/tangela.gif",
        description_audio: tangela_audio,
    },
    {
        pokemon: "Kangaskhan",
        number: "0115",
        description: "Kangaskhan, the Parent Pokémon. Once approaching extinction, they are now protected by law and inhabit the Safari Zone. The Kangaskhan is a rare Pokémon which raises its children in its protective pouch. Approach with extreme caution.",
        type: ["Normal"],
        card: kangaskhan,
        gif: "https://projectpokemon.org/images/normal-sprite/kangaskhan.gif",
        description_audio: kangaskhan_audio,
    },
    {
        pokemon: "Horsea",
        number: "0116",
        description: "Horsea, the Dragon Pokémon. Known to shoot down flying bugs with precision blasts of ink from the surface of the water. In this Pokémon species, thousands of eggs hatch every spring and then the male raises them.",
        type: ["Water"],
        card: horsea,
        gif: "https://projectpokemon.org/images/normal-sprite/horsea.gif",
        description_audio: horsea_audio,
    },
    {
        pokemon: "Seadra",
        number: "0117",
        description: "Seadra, the Dragon Pokémon. The evolved form of Horsea. Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail. The quills that cover its body can render its victim unconscious.",
        type: ["Water"],
        card: seadra,
        gif: "https://projectpokemon.org/images/normal-sprite/seadra.gif",
        description_audio: seadra_audio,
    },
    {
        pokemon: "Goldeen",
        number: "0118",
        description: "Goldeen, the Goldfish Pokémon. Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen. When it is time for them to lay eggs, Goldeen form schools and swim up river.",
        type: ["Water"],
        card: goldeen,
        gif: "https://projectpokemon.org/images/normal-sprite/goldeen.gif",
        description_audio: goldeen_audio,
    },
    {
        pokemon: "Seaking",
        number: "0119",
        description: "Seaking, the Goldfish Pokémon. The evolved form of Goldeen. It is the male's job to make a nest by carving out boulders in a stream using the horn on its head. Its sharp drill-like horn is capable of crushing even stone.",
        type: ["Water"],
        card: seaking,
        gif: "https://projectpokemon.org/images/normal-sprite/seaking.gif",
        description_audio: seaking_audio,
    },
    {
        pokemon: "Staryu",
        number: "0120",
        description: "Staryu, the Star Shape Pokémon. An enigmatic Pokémon that can effortlessly regenerate any appendage it loses in battle.",
        type: ["Water"],
        card: staryu,
        gif: "https://projectpokemon.org/images/normal-sprite/staryu.gif",
        description_audio: staryu_audio,
    },
    {
        pokemon: "Starmie",
        number: "0121",
        description: "Starmie, the mysterious Pokémon. This Pokémon has an organ known as its core. The organ glows in seven colors when Starmie is unleashing its potent psychic powers. Some people value the core as a gem.",
        type: ["Water", "Psychic"],
        card: starmie,
        gif: "https://projectpokemon.org/images/normal-sprite/starmie.gif",
        description_audio: starmie_audio,
    },
    {
        pokemon: "Mr. Mime",
        number: "0122",
        description: "Mr. Mime, the Barrier Pokémon. It uses pantomime to make actual walls appear. If interrupted while it is miming, it will slap around the offender with its broad hands.",
        type: ["Psychic", "Fairy"],
        card: mr_mime,
        gif: "https://projectpokemon.org/images/normal-sprite/mr.mime.gif",
        description_audio: mr_mime_audio,
    },
    {
        pokemon: "Scyther",
        number: "0123",
        description: "Scyther, the Mantis Pokémon. Its claws are sharp as swords, and it is a powerful flyer. With ninja-like agility and speed, it can create the illusion that there is more than one.",
        type: ["Bug", "Flying"],
        card: scyther,
        gif: "https://projectpokemon.org/images/normal-sprite/scyther.gif",
        description_audio: scyther_audio,
    },
    {
        pokemon: "Jynx",
        number: "0124",
        description: "Jynx, the Human Shape Pokémon. This Pokémon has some very unusual powers. It seductively wiggles its hips as it walks which can cause people to dance in unison with it.",
        type: ["Ice", "Psychic"],
        card: jynx,
        gif: "https://projectpokemon.org/images/normal-sprite/jynx.gif",
        description_audio: jynx_audio,
    },
    {
        pokemon: "Electabuzz",
        number: "0125",
        description: "Electabuzz, the Electric Pokémon. It appears near power plants, and because it eats electricity, it can cause blackouts.",
        type: ["Electric"],
        card: electabuzz,
        gif: "https://projectpokemon.org/images/normal-sprite/electabuzz.gif",
        description_audio: electabuzz_audio,
    },
    {
        pokemon: "Magmar",
        number: "0126",
        description: "Magmar, the Spitfire Pokémon. Born in an active volcano, its body is always cloaked in flames. Magmar burns with an orange glow that enables it to hide perfectly among flames.",
        type: ["Fire"],
        card: magmar,
        gif: "https://projectpokemon.org/images/normal-sprite/magmar.gif",
        description_audio: magmar_audio,
    },
    {
        pokemon: "Pinsir",
        number: "0127",
        description: "Pinsir, the Stag Beetle Pokémon. If it fails to crush the victim in its pincers, it will swing it around and toss it hard.",
        type: ["Bug"],
        card: pinsir,
        gif: "https://projectpokemon.org/images/normal-sprite/pinsir.gif",
        description_audio: pinsir_audio,
    },
    {
        pokemon: "Tauros",
        number: "0128",
        description: "Tauros, the Wild Bull Pokémon. When it targets an enemy, it charges furiously while whipping its body with its long tails. When whipping itself with its three tails, its tackle is a powerful, destructive force.",
        type: ["Normal"],
        card: tauros,
        gif: "https://projectpokemon.org/images/normal-sprite/tauros.gif",
        description_audio: tauros_audio,
    },
    {
        pokemon: "Magikarp",
        number: "0129",
        description: "Magikarp, the Fish Pokémon. In the distant past, it was somewhat stronger than the horribly weak descendants that exist today. They can live in the dirtiest of water, and jump very high on rare occasions.",
        type: ["Water"],
        card: magikarp,
        gif: "https://projectpokemon.org/images/normal-sprite/magikarp.gif",
        description_audio: magikarp_audio,
    },
    {
        pokemon: "Gyarados",
        number: "0130",
        description: "Gyarados, the Atrocious Pokémon. Rarely seen in the wild. This Pokémon has a vicious temperament, so use extreme caution. Brutally vicious and enormously destructive, it is capable of destroying entire cities in a rage.",
        type: ["Water", "Flying"],
        card: gyarados,
        gif: "https://projectpokemon.org/images/shiny-sprite/gyarados.gif",
        description_audio: gyarados_audio,
    },
    {
        pokemon: "Lapras",
        number: "0131",
        description: "Lapras, the Transport Pokémon. A Pokémon that has been overhunted almost to extinction. This intellectually advanced Pokémon is able to understand human speech. Lapras prefers to carry humans on its back rather than engage in Pokémon battle.",
        type: ["Water", "Ice"],
        card: lapras,
        gif: "https://projectpokemon.org/images/normal-sprite/lapras.gif",
        description_audio: lapras_audio,
    },
    {
        pokemon: "Ditto",
        number: "0132",
        description: "Ditto, the Transform Pokémon. Capable of copying an enemy's genetic code to instantly transform itself into a duplicate of the enemy. It is usually a shapeless blob.",
        type: ["Normal"],
        card: ditto,
        gif: "https://projectpokemon.org/images/normal-sprite/ditto.gif",
        description_audio: ditto_audio,
    },
    {
        pokemon: "Eevee",
        number: "0133",
        description: "Eevee, the Evolution Pokémon. Its genetic code is unstable, so it could evolve in a variety of ways. Using a Fire stone will yield Flareon, the flame Pokémon. A Water Stone yields Vaporeon, the bubble jet Pokémon. A Thunder Stone yields Jolteon, the lightning Pokémon.",
        type: ["Normal"],
        card: eevee,
        gif: "https://projectpokemon.org/images/normal-sprite/eevee.gif",
        description_audio: eevee_audio,
    },
    {
        pokemon: "Vaporeon",
        number: "0134",
        description: "Vaporeon, the Bubble Jet Pokémon, and an evolved form of Eevee. The composition of its cells is similar to molecules of water and as such can melt in water.",
        type: ["Water"],
        card: vaporeon,
        gif: "https://projectpokemon.org/images/normal-sprite/vaporeon.gif",
        description_audio: vaporeon_audio,
    },
    {
        pokemon: "Jolteon",
        number: "0135",
        description: "Jolteon, the Lightning Pokémon, and an evolved form of Eevee. When angered or frightened, the hairs on Jolteon's body become like needles that are fired at its opponents. It absorbs negative ions in the atmosphere to blast out 10,000 volts of electricity.",
        type: ["Electric"],
        card: jolteon,
        gif: "https://projectpokemon.org/images/normal-sprite/jolteon.gif",
        description_audio: jolteon_audio,
    },
    {
        pokemon: "Flareon",
        number: "0136",
        description: "Flareon, the Flame Pokémon, and an evolved form of Eevee. It stores some of the air it breathes in its internal flame sac, which heats its body to over 3,000 degrees.",
        type: ["Fire"],
        card: flareon,
        gif: "https://projectpokemon.org/images/normal-sprite/flareon.gif",
        description_audio: flareon_audio,
    },
    {
        pokemon: "Porygon",
        number: "0137",
        description: "Porygon, the Virtual Pokémon. A Pokémon that consists entirely of programming code. Capable of moving freely in cyberspace.",
        type: ["Normal"],
        card: porygon,
        gif: "https://projectpokemon.org/images/normal-sprite/porygon.gif",
        description_audio: porygon_audio,
    },
    {
        pokemon: "Omanyte",
        number: "0138",
        description: "Omanyte, the Spiral Pokémon. Believed to have lived over 2 million years ago. Recent research indicated that it was able to control its buoyancy by storing and releasing air in its shell.",
        type: ["Rock", "Water"],
        card: omanyte,
        gif: "https://projectpokemon.org/images/normal-sprite/omanyte.gif",
        description_audio: omanyte_audio,
    },
    {
        pokemon: "Omastar",
        number: "0139",
        description: "Omastar, the Spiral Pokémon. The evolved form of Omanyte. This prehistoric Pokémon died out when its heavy shell made it impossible to catch prey.",
        type: ["Rock", "Water"],
        card: omastar,
        gif: "https://projectpokemon.org/images/normal-sprite/omastar.gif",
        description_audio: omastar_audio,
    },
    {
        pokemon: "Kabuto",
        number: "0140",
        description: "Kabuto, the Shellfish Pokémon. Though this Pokémon is now believed to be extinct, it had a hard shell and used the eyes on its back while hiding on the sea floor.",
        type: ["Rock", "Water"],
        card: kabuto,
        gif: "https://projectpokemon.org/images/normal-sprite/kabuto.gif",
        description_audio: kabuto_audio,
    },
    {
        pokemon: "Kabutops",
        number: "0141",
        description: "Kabutops, the Shellfish Pokémon. The evolved form of Kabuto. Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.",
        type: ["Rock", "Water"],
        card: kabutops,
        gif: "https://projectpokemon.org/images/normal-sprite/kabutops.gif",
        description_audio: kabutops_audio,
    },
    {
        pokemon: "Aerodactyl",
        number: "0142",
        description: "Aerodactyl, the Fossil Pokémon. Aerodactyl is a ferocious Pokémon from ancient times that is now believed to be extinct. It goes for the enemy's throat with its serrated saw-like fangs.",
        type: ["Rock", "Flying"],
        card: aerodactyl,
        gif: "https://projectpokemon.org/images/normal-sprite/aerodactyl.gif",
        description_audio: aerodactyl_audio,
    },
    {
        pokemon: "Snorlax",
        number: "0143",
        description: "Snorlax, the Sleeping Pokémon. Snorlax wakes only to eat and devours nearly 900 pounds of food per day. As its rotund bulk builds, it becomes steadily more slothful.",
        type: ["Normal"],
        card: snorlax,
        gif: "https://projectpokemon.org/images/normal-sprite/snorlax.gif",
        description_audio: snorlax_audio,
    },
    {
        pokemon: "Articuno",
        number: "0144",
        description: "Articuno, the Freeze Pokémon. This legendary bird Pokémon can create blizzards by freezing moisture in the air. Articuno is said to appear to doomed people who are lost in icy mountains.",
        type: ["Ice", "Flying"],
        card: articuno,
        gif: "https://projectpokemon.org/images/normal-sprite/articuno.gif",
        description_audio: articuno_audio,
    },
    {
        pokemon: "Zapdos",
        number: "0145",
        description: "Zapdos, the Electric Pokémon. This legendary bird Pokémon is said to live in thunder clouds where it controls lightning bolts at will.",
        type: ["Electric", "Flying"],
        card: zapdos,
        gif: "https://projectpokemon.org/images/normal-sprite/zapdos.gif",
        description_audio: zapdos_audio,
    },
    {
        pokemon: "Moltres",
        number: "0146",
        description: "Moltres, the Flame Pokémon. The legendary bird of fire. Every flap of its wings creates a dazzling flash of flames.",
        type: ["Fire", "Flying"],
        card: moltres,
        gif: "https://projectpokemon.org/images/normal-sprite/moltres.gif",
        description_audio: moltres_audio,
    },
    {
        pokemon: "Dratini",
        number: "0147",
        description: "Dratini, the Dragon Pokémon. Long considered a mythical Pokémon until recently when a small colony was found living underwater. Dratini sheds its skin as it grows, often doing so while hidden behind large, powerful waterfalls.",
        type: ["Dragon"],
        card: dratini,
        gif: "https://projectpokemon.org/images/normal-sprite/dratini.gif",
        description_audio: dratini_audio,
    },
    {
        pokemon: "Dragonair",
        number: "0148",
        description: "Dragonair, the Dragon Pokémon. A mystical Pokémon that exudes a gentle aura. Dragonair has the ability to manipulate the elements as it wishes.",
        type: ["Dragon"],
        card: dragonair,
        gif: "https://projectpokemon.org/images/normal-sprite/dragonair.gif",
        description_audio: dragonair_audio,
    },
    {
        pokemon: "Dragonite",
        number: "0149",
        description: "Dragonite, the Dragon Pokémon. Dragonite is said to live in the sea. With its small wings and large body, it can fly faster than the speed of sound. Its intelligence is said to match that of humans.",
        type: ["Dragon", "Flying"],
        card: dragonite,
        gif: "https://projectpokemon.org/images/normal-sprite/dragonite.gif",
        description_audio: dragonite_audio,
    },
    {
        pokemon: "Mewtwo",
        number: "0150",
        description: "Mewtwo, the Genetic Pokémon. Its DNA is almost the same as Mew's. However, its size and disposition are vastly different. It was created by a scientist after years of horrific gene splicing and DNA engineering experiments.",
        type: ["Psychic"],
        card: mewtwo,
        gif: "https://projectpokemon.org/images/normal-sprite/mewtwo.gif",
        description_audio: mewtwo_audio,
    },
    {
        pokemon: "Mew",
        number: "0151",
        description: "Mew, the New Species Pokémon. Mew is said to possess the genetic composition of all Pokémon. It is capable of making itself invisible at will. So rare that it is still said to be a mirage by many experts. Only a few people have ever seen it worldwide.",
        type: ["Psychic"],
        card: mew,
        gif: "https://projectpokemon.org/images/normal-sprite/mew.gif",
        description_audio: mew_audio,
    },
    {
        pokemon: "",
        number: "",
        description: "There is no data. There are still Pokémon yet to be identified.",
        type: [],
        card: "",
        gif: "https://cdn.shopify.com/s/files/1/0388/3771/4989/files/POKEMON_LOGO.png?v=1650302988",
        description_audio: unknown_audio,
    }
];
